server:
  port: 8090

logging:
  level:
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

management.endpoints.web.exposure.include: metrics, loggers
management.tracing.sampling.probability: 1.0